// Mocks generated by Mockito 5.4.5 from annotations
// in quize_app/test/src/presentation/profile/view_mdoel/profile_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:quize_app/core/api/common/api_result.dart' as _i5;
import 'package:quize_app/src/data/model/request/update_profile_request.dart'
    as _i10;
import 'package:quize_app/src/domain/entities/app_user_entity.dart' as _i6;
import 'package:quize_app/src/domain/repositories/auth_repository.dart' as _i2;
import 'package:quize_app/src/domain/use_case/auth_use_case/edit_profile_use_case.dart'
    as _i9;
import 'package:quize_app/src/domain/use_case/auth_use_case/get_profile_data_use_case.dart'
    as _i3;
import 'package:quize_app/src/domain/use_case/auth_use_case/logout_use_case.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthRepository_0 extends _i1.SmartFake
    implements _i2.AuthRepository {
  _FakeAuthRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetProfileDataUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProfileDataUseCase extends _i1.Mock
    implements _i3.GetProfileDataUseCase {
  @override
  _i2.AuthRepository get authRepository => (super.noSuchMethod(
        Invocation.getter(#authRepository),
        returnValue: _FakeAuthRepository_0(
          this,
          Invocation.getter(#authRepository),
        ),
        returnValueForMissingStub: _FakeAuthRepository_0(
          this,
          Invocation.getter(#authRepository),
        ),
      ) as _i2.AuthRepository);

  @override
  _i4.Future<_i5.Result<_i6.AppUserEntity>> invoke() => (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [],
        ),
        returnValue: _i4.Future<_i5.Result<_i6.AppUserEntity>>.value(
            _i7.dummyValue<_i5.Result<_i6.AppUserEntity>>(
          this,
          Invocation.method(
            #invoke,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i5.Result<_i6.AppUserEntity>>.value(
                _i7.dummyValue<_i5.Result<_i6.AppUserEntity>>(
          this,
          Invocation.method(
            #invoke,
            [],
          ),
        )),
      ) as _i4.Future<_i5.Result<_i6.AppUserEntity>>);
}

/// A class which mocks [LogoutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutUseCase extends _i1.Mock implements _i8.LogoutUseCase {
  @override
  _i2.AuthRepository get authRepository => (super.noSuchMethod(
        Invocation.getter(#authRepository),
        returnValue: _FakeAuthRepository_0(
          this,
          Invocation.getter(#authRepository),
        ),
        returnValueForMissingStub: _FakeAuthRepository_0(
          this,
          Invocation.getter(#authRepository),
        ),
      ) as _i2.AuthRepository);

  @override
  _i4.Future<_i5.Result<bool>> invoke() => (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [],
        ),
        returnValue:
            _i4.Future<_i5.Result<bool>>.value(_i7.dummyValue<_i5.Result<bool>>(
          this,
          Invocation.method(
            #invoke,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i5.Result<bool>>.value(_i7.dummyValue<_i5.Result<bool>>(
          this,
          Invocation.method(
            #invoke,
            [],
          ),
        )),
      ) as _i4.Future<_i5.Result<bool>>);
}

/// A class which mocks [EditProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditProfileUseCase extends _i1.Mock
    implements _i9.EditProfileUseCase {
  @override
  _i2.AuthRepository get authRepository => (super.noSuchMethod(
        Invocation.getter(#authRepository),
        returnValue: _FakeAuthRepository_0(
          this,
          Invocation.getter(#authRepository),
        ),
        returnValueForMissingStub: _FakeAuthRepository_0(
          this,
          Invocation.getter(#authRepository),
        ),
      ) as _i2.AuthRepository);

  @override
  _i4.Future<_i5.Result<_i6.AppUserEntity>> invoke(
          {required _i10.UpdateProfileRequest? updateProfileRequest}) =>
      (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [],
          {#updateProfileRequest: updateProfileRequest},
        ),
        returnValue: _i4.Future<_i5.Result<_i6.AppUserEntity>>.value(
            _i7.dummyValue<_i5.Result<_i6.AppUserEntity>>(
          this,
          Invocation.method(
            #invoke,
            [],
            {#updateProfileRequest: updateProfileRequest},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i5.Result<_i6.AppUserEntity>>.value(
                _i7.dummyValue<_i5.Result<_i6.AppUserEntity>>(
          this,
          Invocation.method(
            #invoke,
            [],
            {#updateProfileRequest: updateProfileRequest},
          ),
        )),
      ) as _i4.Future<_i5.Result<_i6.AppUserEntity>>);
}
