// Mocks generated by Mockito 5.4.5 from annotations
// in quize_app/test/src/presentation/verify_reset_code/view_model/verify_reset_code_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:quize_app/core/api/common/api_result.dart' as _i5;
import 'package:quize_app/src/data/model/request/verify_reset_code_request.dart'
    as _i7;
import 'package:quize_app/src/domain/entities/success_auth_entity.dart' as _i6;
import 'package:quize_app/src/domain/repositories/auth_repository.dart' as _i2;
import 'package:quize_app/src/domain/use_case/auth_use_case/verify_reset_code_use_case.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthRepository_0 extends _i1.SmartFake
    implements _i2.AuthRepository {
  _FakeAuthRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [VerifyResetCodeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifyResetCodeUseCase extends _i1.Mock
    implements _i3.VerifyResetCodeUseCase {
  @override
  _i2.AuthRepository get authRepository => (super.noSuchMethod(
        Invocation.getter(#authRepository),
        returnValue: _FakeAuthRepository_0(
          this,
          Invocation.getter(#authRepository),
        ),
        returnValueForMissingStub: _FakeAuthRepository_0(
          this,
          Invocation.getter(#authRepository),
        ),
      ) as _i2.AuthRepository);

  @override
  _i4.Future<_i5.Result<_i6.SuccessAuthEntity>> invoke(
          {required _i7.VerifyResetCodeRequest? verifyResetCodeRequest}) =>
      (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [],
          {#verifyResetCodeRequest: verifyResetCodeRequest},
        ),
        returnValue: _i4.Future<_i5.Result<_i6.SuccessAuthEntity>>.value(
            _i8.dummyValue<_i5.Result<_i6.SuccessAuthEntity>>(
          this,
          Invocation.method(
            #invoke,
            [],
            {#verifyResetCodeRequest: verifyResetCodeRequest},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i5.Result<_i6.SuccessAuthEntity>>.value(
                _i8.dummyValue<_i5.Result<_i6.SuccessAuthEntity>>(
          this,
          Invocation.method(
            #invoke,
            [],
            {#verifyResetCodeRequest: verifyResetCodeRequest},
          ),
        )),
      ) as _i4.Future<_i5.Result<_i6.SuccessAuthEntity>>);
}
